### ISSUE TITLE
Cannot compile this

### ISSUE THREAD

**Issue by wingerse** [terahxluna/Agar.net#2]
Whenever I run the project, it says: 

`An unhandled exception of type 'System.BadImageFormatException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'sfmlnet-system-2, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.`

Am I missing something?

**Comment by wingerse** [comment]
Never mind, I am not familiar with SFML. Looks like I needed to have csfml unmanaged dlls in the execution path.

**Comment by terahlunah** [comment]
No problem.
But you should know that the server is not up to date with the latest version of agario, I don't have the time to maintain it alone right now.
